version: "3.8"
services:
  mysql:
    image: mysql:8
    restart: always
    container_name: scopix_online
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: scopix_db
      MYSQL_USER: admins
      MYSQL_PASSWORD: admins
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
